/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#fdf7ef',
        'surface': '#fff8ef',
        'primary': '#033130',
        'primary-container': '#e6f7f6',
        'secondary': '#1e6c2b',
        'secondary-fixed': '#a5f6a3',
        'tertiary': '#2e2843',
        'tertiary-fixed': '#e7deff',
        'surface-variant': '#ece7f6',
        'surface-container-low': '#f9f3ea',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ede7de',
        'surface-container-highest': '#e8e2d9',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#1d1b16',
        'on-surface-variant': '#404847',
        'on-primary-container': '#033130',
        'on-secondary-container': '#267330',
        'on-tertiary-container': '#b2aacc',
        'on-tertiary-fixed-variant': '#494360',
        'on-primary-fixed': '#00201f',
        'on-secondary-fixed': '#002105',
        'on-tertiary-fixed': '#1d1732',
        'outline-variant': '#c0c8c7',
        'outline': '#717978',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-primary': '#a4cfcb',
        'inverse-surface': '#33302a',
        'inverse-on-surface': '#f6f0e7',
        'surface-tint': '#3d6563',
        'surface-bright': '#fff8ef',
        'surface-dim': '#dfd9d0',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif']
      },
      borderRadius: {
        DEFAULT: '2rem',
        lg: '3rem',
        xl: '4rem',
        full: '9999px',
      },
      boxShadow: {
        'editorial': '0 40px 60px -15px rgba(29, 27, 22, 0.06)',
        '2xl': '0 25px 50px -12px rgba(0,0,0,0.25)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
